version: 2.1

orbs:
  maven: circleci/maven@1.1
  sonatype: sonatype-nexus-community/circleci-maven-release-orb@0.0.16
  sonatype-dryrun: sonatype-nexus-community/circleci-maven-release-orb@0.0.16

executors:
  openjdk8:
    docker:
      - image: circleci/openjdk:8-jdk

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8u171-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS=-Xmx3600m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # check
      - run: mvn apache-rat:check

      # run test and package
      - run: mvn clean package

      # Save JUnit result.
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit

      # run site
      - run: mvn site

      - run:
          command: |
            cp -r ./target/site ~/site
      - store_artifacts:
          path: ~/site
  notify:
    executor: openjdk8
    steps:
      - run: echo "notify"

custom_filters:
  main_only: &merge_only
    filters:
      branches:
        only:
          - main
          - old-0.0.0
  main_ignore: &merge_ignore
    filters:
      branches:
        ignore:
          - main
          - old-0.0.0

workflows:
  build-and-test:
    jobs:
      - build:
          <<: *merge_ignore
  run-release:
    jobs:
      - build:
          <<: *merge_only
      - sonatype-dryrun/run-maven-release:
          <<: *merge_only
          requires:
            - build
          mvn-release-perform-command: |
            mvn --batch-mode validate release:perform -DdryRun=true -s .circleci/.maven.xml
          mvn-release-prepare-command: |
            mvn --batch-mode validate release:prepare -DscmCommentPrefix="[skip ci][maven-release-plugin] " -DdryRun=true -s .circleci/.maven.xml
          ssh-fingerprints: 68:c0:1b:f2:32:d4:0d:c5:6f:56:1e:d8:c4:54:56:c9
      - notify:
          <<: *merge_only
          requires:
            - sonatype-dryrun/run-maven-release
      - approve:
          type: approval
          <<: *merge_only
          requires:
            - notify
      - sonatype/run-maven-release:
          <<: *merge_only
          requires:
            - approve
          mvn-release-perform-command: |
            mvn --batch-mode validate release:perform -s .circleci/.maven.xml
          mvn-release-prepare-command: |
            mvn --batch-mode validate release:prepare -DscmCommentPrefix="[skip ci][maven-release-plugin] " .circleci/.maven.xml
          ssh-fingerprints: 68:c0:1b:f2:32:d4:0d:c5:6f:56:1e:d8:c4:54:56:c9